name: Deploy FastAPI to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Клонування репозиторію
    - name: Checkout code
      uses: actions/checkout@v3

    # Налаштування підключення до EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }} # Публічна IP-адреса вашого EC2 інстансу
        username: ${{ secrets.EC2_USER }} # Ім'я користувача для SSH (наприклад, ec2-user)
        key: ${{ secrets.EC2_PRIVATE_KEY }} # Приватний SSH-ключ
        script: |
          # Оновлення системи
          sudo yum update -y || sudo apt update -y

          # Встановлення Docker (якщо не встановлено)
          if ! command -v docker &> /dev/null; then
            sudo yum install -y docker || sudo apt install -y docker.io
            sudo service docker start || sudo systemctl start docker
            sudo usermod -aG docker $USER
          fi

          # Створення робочої директорії для проєкту
          PROJECT_DIR="/home/ec2-user/fastapi-app"
          sudo mkdir -p $PROJECT_DIR
          sudo chown $USER:$USER $PROJECT_DIR
          cd $PROJECT_DIR

          # Завантаження останнього коду з GitHub
          if [ ! -d ".git" ]; then
            git init
            git remote add origin git@github.com:${{ github.repository }}.git
          fi
          git fetch origin
          git reset --hard origin/main

          # Збирання Docker-образу
          docker build -t fastapi-app:latest .

          # Зупинка та видалення попереднього контейнера
          docker stop fastapi-app || true
          docker rm fastapi-app || true

          # Запуск нового контейнера
          docker run -d -p 80:8000 --name fastapi-app fastapi-app:latest

          echo "Deployment completed!"
